apiVersion: v1
kind: Namespace
metadata:
  name: falcon-kac-system
  labels:
    app.kubernetes.io/name: falcon-kac
    # gatekeeper.exclude/enforced-repos: GMI
    # gatekeeper.exclude/psp.privilege-escalation: ""
