name: Automated Upgrades

on:
  workflow_dispatch:
    inputs:
      kac-version:
        description: 'KAC version'
        required: true
      sensor-version:
        description: 'Sensor version'
        required: true
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - production
          - 'dev & nonprod'

env:
  FALCON_KAC_TEMPLATE: |-
    'apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: falcon-kac-deploy
    target:
      group: kustomize.toolkit.fluxcd.io
    kind: Kustomization
    name: falcon-kac-deploy
    namespace: flux-system
    patch: |-
      - op: add
        path: \spec\patches\-\n
        value:\n
          target:\n
            group: helm.toolkit.fluxcd.io\n
            kind: HelmRelease\n
            name: falcon-kac\n
            namespace: falcon-kac-system\n
          patch: |-\n
            - op: replace\n
              path: \spec\values\image\tag\n
              value: "7.27.0-2502.Release.US-2"'

jobs:
  create-prs:
    runs-on: ubuntu-latest
    if: inputs.environment == 'dev & nonprod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to allow for accurate branch creation
      - name: Update KAC and Sensor versions
        run: |
          kac_template='apiVersion: builtin
                        kind: PatchTransformer
                        metadata:
                          name: falcon-kac-deploy
                        target:
                          group: kustomize.toolkit.fluxcd.io
                        kind: Kustomization
                        name: falcon-kac-deploy
                        namespace: flux-system
                        patch: |-
                          - op: add
                            path: \spec\patches\-\n
                            value:\n
                              target:\n
                                group: helm.toolkit.fluxcd.io\n
                                kind: HelmRelease\n
                                name: falcon-kac\n
                                namespace: falcon-kac-system\n
                              patch: |-\n
                                - op: replace\n
                                  path: \spec\values\image\tag\n
                                  value: "${{ inputs.kac-version }}"'
          echo "Updating KAC and Sensor versions..."
          sed -i -z 's|#version.*|        - op: replace\n          path: /spec/values/node/image/tag\n          value: "${{ inputs.sensor-version }}"|' config/base/cluster/gke-pe-dev/transformers/version.yaml
          echo "$kac_template" > config/base/cluster/gke-pe-dev/transformers/kac-transformer.yaml
          echo "KAC version: ${{ inputs.kac-version }}"
          echo "Sensor version: ${{ inputs.sensor-version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Upgrade KAC and Sensor"
          body: |
            Upgrade KAC to ${{ inputs.kac-version }} and Sensor to ${{ inputs.sensor-version }}.
          branch: "upgrade-${{ github.run_id }}" # Unique branch name
          commit-message: "Upgrade KAC and Sensor"
