name: Automated Upgrades

on:
  workflow_dispatch:
    inputs:
      kac-version:
        description: 'KAC version'
        required: true
      sensor-version:
        description: 'Sensor version'
        required: true

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to allow for accurate branch creation

      - name: Update KAC and Sensor versions
        run: |
          echo "Updating KAC and Sensor versions..."
          sed -i "s/kac-version: .*/kac-version: ${{ inputs.kac-version }}/" verion.yaml
          sed -i "s/sensor-version: .*/sensor-version: ${{ inputs.sensor-version }}/" verion.yaml
          echo "KAC version: ${{ inputs.kac-version }}"
          echo "Sensor version: ${{ inputs.sensor-version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Upgrade KAC and Sensor"
          body: |
            Upgrade KAC to ${{ inputs.kac-version }} and Sensor to ${{ inputs.sensor-version }}.
          branch: "upgrade-${{ github.run_id }}" # Unique branch name
          commit-message: "Upgrade KAC and Sensor"
