name: Automated Upgrades

on:
  workflow_dispatch:
    inputs:
      kac-version:
        description: 'KAC version'
        required: true
      sensor-version:
        description: 'Sensor version'
        required: true
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - production
          - 'dev & nonprod'

jobs:
  create-prs:
    runs-on: ubuntu-latest
    if: inputs.environment == 'dev & nonprod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to allow for accurate branch creation
      - name: Update KAC and Sensor versions
        run: |
          echo "Grabbing Falcon-KAC template..."
          echo 'FALCON_KAC_TEMPLATE<<EOF' >> $GITHUB_ENV
          cat .github/templates/falcon-kac.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "Updating KAC and Sensor versions..."
          sed -i -z 's|#version.*|        - op: replace\n          path: /spec/values/node/image/tag\n          value: "${{ inputs.sensor-version }}"|' config/base/cluster/gke-pe-dev/transformers/version.yaml
          echo "$FALCON_KAC_TEMPLATE" > config/base/cluster/gke-pe-dev/transformers/kac-transformer.yaml
          echo "KAC version: ${{ inputs.kac-version }}"
          echo "Sensor version: ${{ inputs.sensor-version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Upgrade KAC and Sensor"
          body: |
            Upgrade KAC to ${{ inputs.kac-version }} and Sensor to ${{ inputs.sensor-version }}.
          branch: "upgrade-${{ github.run_id }}" # Unique branch name
          commit-message: "Upgrade KAC and Sensor"
